
# kp1/deseq2 analysis

## 1. prepare deseq2 input from rsem output

https://bioconductor.org/packages/3.7/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#transcript-abundance-files-and-tximport-input

http://bioconductor.org/packages/release/bioc/vignettes/tximport/inst/doc/tximport.html#rsem

check which R is compatible with tximport,
use if none compatible /users/lfresard/R_3.3.2/bin/R
```{r}
which R
module avail
```

```{bash}
module load r/3.4.2
R
```

install deseq and dependent packages
```{r}
source("https://bioconductor.org/biocLite.R")
biocLite("tximport")
biocLite("readr")
biocLite("DESeq2")
biocLite("pcaExplorer")
biocLite("regionReport")
biocLite("ReportingTools")
```

load sample file
```{r}
dir <- "~/projects/kp1/"
samples <- read.table(file.path(dir, "sample", "kp1_sample_table.txt"), header=TRUE)
```

prepare deseq input data structure
```{r}
library("tximport")
library("readr")
files <- file.path(dir, "rsem", "rsem_output", paste0(samples$rna_lib, ".Aligned.toTranscriptome.genes.results"))
names(files) <- paste0("rna_", samples$rna_lib)
txi.rsem <- tximport(files, type = "rsem", txIn = FALSE, txOut = FALSE)
head(txi.rsem$counts)
```

https://support.bioconductor.org/p/92763/
edit effect length 0
```{r}
txi.rsem$length[txi.rsem$length == 0] <- 1
```

## 2. deseq2 and p-values

```{r}
library("DESeq2")
ddsTxi <- DESeqDataSetFromTximport(txi.rsem, colData = samples, design = ~ condition)
ddsTxi <- DESeq(ddsTxi)
resTxi = results(ddsTxi)
```

```{r}
save.image(file="~/projects/kp1/deseq/deseq_output/kp1_deseq.RData")
savehistory("~/projects/kp1/deseq/deseq_output/kp1_deseq.Rhistory")
```

## 3. ma plot, html report

https://bioconductor.org/packages/3.7/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#rich-visualization-and-reporting-of-results

http://bioconductor.org/packages/release/bioc/vignettes/pcaExplorer/inst/doc/pcaExplorer.html

http://bioconductor.org/packages/release/bioc/html/ReportingTools.html

http://bioconductor.org/packages/release/bioc/html/regionReport.html
```{r}
library('ggplot2')
library('regionReport')
dir_deseq <- file.path(dir, "kp1_supp", "deseq")
dir.create(dir_deseq, showWarnings = FALSE, recursive = TRUE)
report <- DESeq2Report(dds, project = 'kp1 DESeq2 HTML report',
    intgroup = c('condition', 'type'), outdir = dir_deseq,
    output = 'kp1_deseq_index', theme = theme_bw())
```

## 4. pca among samples

https://bioconductor.org/packages/3.7/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#principal-component-plot-of-the-samples
https://bioconductor.org/packages/3.7/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#data-quality-assessment-by-sample-clustering-and-visualization

## 5. vst (variance stablizing transformation)

https://bioconductor.org/packages/3.7/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#variance-stabilizing-transformation





